[project]
name = "brief-3-cardprofiler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mohammed Bentalb", email = "mohammedbentalb0@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fg-data-profiling>=4.20.0",
    "ipykernel>=7.4.0",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=2.3.3",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]

[project.scripts]
brief-3-cardprofiler = "src:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "src"
module-root = ""

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
    "pip>=26.2.1",
]
